package com.samplespace.device_upgrade;

import com.samplespace.device_upgrade.customer;
import java.util.Date;
import java.text.SimpleDateFormat;

function boolean chkContractEndDate(String contractEndDate){
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date passedDate = dateFormat.parse(contractEndDate);
    return passedDate.after(new Date());
}



rule "chkBalanceContract"
    ruleflow-group "chkContract"
	when
		offer: customer(chkContractEndDate(customer.contract.endDate))
	then
		offer.setPhone("15");
	end