package com.samplespace.device_upgrade;

import com.samplespace.device_upgrade.customer;
import com.samplespace.device_upgrade.custRuleChkRes;

import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.temporal.ChronoUnit;
import java.time.LocalDate;

function boolean chkContractEndDate(String contractEndDate, custRuleChkRes upgRes) {
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date passedDate = dateFormat.parse(contractEndDate);
    upgRes.setIsContractOver(passedDate.after(new Date()));
    return passedDate.after(new Date());
}

function boolean getBalance(int monthlyPay, String contractEndDate, custRuleChkRes upgRes) {
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String currDate = dateFormat.format(new Date());
    Date passedDate = dateFormat.parse(contractEndDate);
    //passedDate.after((int) Math.ceil((double) ChronoUnit.DAYS.between(LocalDate.parse(currDate), LocalDate.parse(contractEndDate))/30) * monthlyPay));
    //return Math.ceil((double) ChronoUnit.DAYS.between(LocalDate.parse(currDate), LocalDate.parse(contractEndDate))/30) * monthlyPay;
    return true;
}

rule "chkBalanceContract"
    ruleflow-group "chkContract"
	when
		upgRes: custRuleChkRes()
		offer: customer(chkContractEndDate(customer.contract.endDate, upgRes), getBalance(customer.contract.monthlyPayment, customer.contract.endDate, upgRes))
	then
        upgRes.setIsCreditOk(false);
	end