package com.samplespace.device_upgrade;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class contract implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public contract() {
    }




}