package com.samplespace.device_upgrade;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class custRuleChkRes implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Is Contract Over")
	private java.lang.Boolean isContractOver;
	@org.kie.api.definition.type.Label("Balance Due")
	private Integer balanceDue;
	@org.kie.api.definition.type.Label("Is Credit Ok")
	private java.lang.Boolean isCreditOk;

	public custRuleChkRes() {
	}

	public java.lang.Boolean getIsContractOver() {
		return this.isContractOver;
	}

	public void setIsContractOver(java.lang.Boolean isContractOver) {
		this.isContractOver = isContractOver;
	}

	public java.lang.Boolean getIsCreditOk() {
		return this.isCreditOk;
	}

	public void setIsCreditOk(java.lang.Boolean isCreditOk) {
		this.isCreditOk = isCreditOk;
	}

	public java.lang.Integer getBalanceDue() {
		return this.balanceDue;
	}

	public void setBalanceDue(java.lang.Integer balanceDue) {
		this.balanceDue = balanceDue;
	}

	public custRuleChkRes(java.lang.Boolean isContractOver,
			java.lang.Integer balanceDue, java.lang.Boolean isCreditOk) {
		this.isContractOver = isContractOver;
		this.balanceDue = balanceDue;
		this.isCreditOk = isCreditOk;
	}

}